---
- hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Stop harmony
    systemd:
      name: harmony
      state: stopped

  - name: Remove db, latest, and .hmykey
    become_user: harmony
    shell: "rm -rf {{ harmony_home }}/harmony_db_* {{ harmony_home }}/latest/* {{ harmony_home }}/.hmykey"
    args:
      warn: no

  - name: Start harmony
    systemd:
      name: harmony
      state: started
