---
- hosts: all
  gather_facts: true
  become: true
  pre_tasks:
  - include_vars: defaults/main.yml

  tasks:
  - name: Get keystore filenames
    find:
      paths: "{{ wallet_home }}/.hmy/keystore"
    register: keystore

  - name: Fetch keystore
    fetch:
      src: "{{ item.path }}"
      dest: "credentials/{{ ansible_hostname }}/keystore/"
      flat: true
    with_items: "{{ keystore.files }}"

  - name: Get BLS filenames
    find:
      paths: "{{ wallet_home }}"
      recurse: no
      file_type: file
      patterns:
        - 'UTC--*Z--bls_*'
        - '*.key'
    register: bls

  - name: Fetch BLS
    fetch:
      src: "{{ item.path }}"
      dest: "credentials/{{ ansible_hostname }}/bls/"
      flat: true
    with_items: "{{ bls.files }}"

  - name: Fix permissions
    local_action: file path="credentials" mode=og-rx recurse=true
