---
- hosts: all
  gather_facts: true

  tasks:
  - name: Get keystore filenames
    become: true
    find:
      paths: "{{ wallet_home }}/.hmy/keystore"
    register: keystore

  - name: Fetch keystore
    become: true
    fetch:
      src: "{{ item.path }}"
      dest: "credentials/{{ ansible_hostname }}/keystore/"
      flat: true
    with_items: "{{ keystore.files }}"

  - name: Get BLS filenames
    become: true
    find:
      paths: "{{ wallet_home }}"
      patterns: "UTC--*Z--bls_*"
    register: bls

  - name: Fetch BLS
    become: true
    fetch:
      src: "{{ item.path }}"
      dest: "credentials/{{ ansible_hostname }}/bls/"
      flat: true
    with_items: "{{ bls.files }}"

  - name: Fix permissions
    local_action: file path="credentials" mode=og-rx recurse=true
