---
- hosts: all
  gather_facts: true

  handlers:
  - name: systemd reload handler
    become: true
    systemd:
      daemon_reload: yes
    listen: "systemd reload"

  - name: Reload sysctl
    become: true
    command: "/sbin/sysctl -p /etc/sysctl.d/99-harmony.conf"
    listen: "sysctl reload"

  tasks:
  - import_tasks: tasks/system.yml
  - import_tasks: tasks/upstream.yml
