---
- hosts: all
  gather_facts: true

  tasks:
  - set_fact:
      bn_ma: "/ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9"

  - include_vars:
      file: addresses.json
      name: addresses

  - name: Install harmony bin
    become: true
    copy:
      src: files/bin/harmony
      dest: /usr/local/bin/
      mode: '0755'
      owner: root
      group: root

  - name: Install harmony libs
    become: true
    copy:
      src: "{{ item }}"
      dest: /usr/local/lib/harmony/
      mode: '0755'
      owner: root
      group: root
    with_fileglob:
      - files/bin/lib*

  - name: Install harmonyd daemon wrapper
    become: true
    copy:
      src: files/sbin/harmonyd
      dest: /usr/local/sbin/
      mode: '0755'
      owner: root
      group: root

  - name: Install harmonyd daemon wrapper config
    become: true
    template:
      src: templates/harmonyd.j2
      dest: /etc/default/harmonyd
      mode: '0640'
      owner: harmony
      group: adm

  - name: Install harmonyd systemd unit file
    become: true
    copy:
      src: files/etc/systemd/system/harmony.service
      dest: /etc/systemd/system/
      mode: '0644'
      owner: root
      group: root

  - name: Make harmonyd pidfile directory
    become: true
    file:
      path: /run/harmonyd/
      state: directory
      mode: '0755'
      owner: harmony
      group: harmony

  - name: Add harmony user
    become: true
    user:
      name: harmony
      comment: Harmony Role Account
      create_home: true
      home: /home/harmony/

  - name: Make harmony user keystore
    become: true
    file:
      path: /home/harmony/.hmy/keystore/
      state: directory
      mode: '0755'
      owner: harmony
      group: harmony
      recurse: yes

  - name: Add files to keystore
    become: true
    copy:
      src: "{{ item }}"
      dest: /home/harmony/.hmy/keystore/
      mode: '0640'
      owner: harmony
      group: harmony
    with_fileglob:
      - keystore/{{ ansible_hostname }}/*

  - name: Enable harmony unit file
    become: true
    systemd:
      name: harmony
      daemon_reload: yes
      enabled: yes
      masked: no
