---
- hosts: all
  gather_facts: true
  become: true

  handlers:
  - name: systemd reload handler
    systemd:
      daemon_reload: yes
    listen: "systemd reload"

  - name: Reload sysctl
    command: "/sbin/sysctl -p /etc/sysctl.d/99-harmony.conf"
    listen: "sysctl reload"

  tasks:
  - import_tasks: tasks/system.yml
  - import_tasks: tasks/wrapper.yml
  - import_tasks: tasks/staging.yml
  - import_tasks: tasks/update.yml
    when: staging_bins.changed or staging_libs.changed or staging_checksum.changed
