---
- name: "Run role as a playbook"
  hosts: "{{ inventory | default('all') }}"
  become: true

  pre_tasks:
  - name: "Get git tag"
    shell: git describe --tags --abbrev=4 --dirty --always
    register: git_describe
    delegate_to: localhost
    tags: dev

  roles: [ main ]
