---
- name: "Run role as a playbook"
  hosts: all
  become: true

  pre_tasks:
  - name: "Get git tag"
    shell: git describe --tags --abbrev=4 --dirty --always
    register: git_describe
    delegate_to: localhost

  roles: [ main ]
