---
- hosts: all
  gather_facts: true
  become: true
  pre_tasks:
  - include_vars: defaults/main.yml

  handlers:
  - name: systemd reload handler
    systemd:
      daemon_reload: yes
    listen: "systemd reload"

  tasks:
  - name: Stop harmony
    systemd:
      name: harmony
      state: stopped

  - name: Disable harmony unit file
    systemd:
      name: "{{ harmony_user }}"
      enabled: no
      masked: no

  - name: Remove harmonyd systemd unit file
    file:
      name: /etc/systemd/system/harmony.service
      state: absent
    notify: "systemd reload"

  - name: Remove harmony lib dir
    shell: "rm -rf /usr/local/lib/harmony"
    args:
      warn: no

  - name: Remove harmony bin
    file:
      name: "/usr/local/bin/harmony"
      state: absent

  - name: Remove harmonyd wrapper and sysctl config
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - "/usr/local/sbin/harmonyd"
      - "/etc/default/harmonyd"
      - "/etc/sysctl.d/99-harmony.conf"

  # TODO: revert systemd NPROC and NOFILES

  - name: Remove harmony user
    user:
      name: "{{ harmony_user }}"
      state: absent
    ignore_errors: yes

  - name: Remove home dir
    shell: "rm -rf {{ harmony_home }}"
    args:
      warn: no
