---
- hosts: all
  gather_facts: true

  tasks:
  - name: Stop harmony
    become: true
    systemd:
      name: harmony
      state: stopped

#  - name: Clear harmony db
#   become: true

  - name: Start harmony
    become: true
    systemd:
      name: harmony
      state: started
