---
- name: "***** EXPLORER *****"
  set_fact:
    harmony_mode: "-node_type explorer -public_rpc"
  when: is_explorer

#- name: Make harmony logfile directory
#  file:
#    path: "/var/log/harmonyd"
#    state: directory
#    owner: "{{ harmony_user }}"
#    group: "{{ harmony_user }}"
#    mode: '0755'

- name: Install harmonyd logrotate config
  template:
    src: templates/harmonyd-logrotate.j2
    dest: /etc/logrotate.d/harmonyd
    mode: '0644'
    owner: root
    group: root

- name: Install harmonyd daemon wrapper config
  template:
    src: templates/harmonyd-default.j2
    dest: /etc/default/harmonyd
    mode: '0644'
    owner: root
    group: root
  notify: "harmony restart"

- name: Install harmonyd daemon wrapper
  copy:
    src: files/sbin/harmonyd
    dest: /usr/local/sbin/
    mode: '0755'
    owner: root
    group: root
  notify: "harmony restart"

- name: Install harmony and nodestate_collector systemd unit files
  template:
    src: "templates/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
    owner: root
    group: root
  loop: [ harmony, nodestate-collector ]

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable harmony and nodestate-collector unit files
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  loop: [ harmony, nodestate-collector ]
  notify: "harmony restart"
