---
- name: Install harmony dev bin to staging
  copy:
    src: "{{ dev_bindir }}/harmony"
    dest: "{{ harmony_home }}/staging/harmony-dev"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  register: staging_devbin

- name: Transfer harmony dev bin to live
  import_tasks: update.yml
  vars:
    item: "harmony-dev"
  when: staging_devbin.changed
  tags: [never, dev]
