---
- name: Install upstream harmony utils
  copy:
    src: "files/bin/{{ item }}"
    dest: "{{ harmony_home }}/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  with_items:
    - node.sh
    - mystatus.sh
    - hmy.sh
    - hmy
    - tui
    - bootnode

- name: Install harmony libs
  copy:
    src: "{{ item }}"
    dest: "{{ harmony_home }}"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  with_fileglob:
    - files/bin/lib*
# notify: harmony restart # harmony is statically linked now

- name: Install harmony checksum file
  copy:
    src: "files/bin/harmony-checksums.txt"
    dest: "{{ harmony_home }}/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  register: checksums

- name: Install harmony bins to staging
  copy:
    src: "files/bin/{{ item }}"
    dest: "{{ harmony_home }}/staging/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  with_items:
    - harmony
  register: staging_bins

- name: Transfer harmony bins to live
  include_tasks: update.yml
  with_items:
    - harmony
  when: checksums.changed or staging_bins.changed
