---
- name: Install harmony binary to staging
  get_url:
    url: "https://github.com/harmony-one/harmony/releases/download/v{{ harmony_version }}/harmony"
    dest: "{{ harmony_home }}/staging/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: 0755
  register: staging_bin

- name: Transfer harmony bins to live
  include_tasks: update.yml
  with_items:
    - harmony
  when: staging_bin.changed
