---
- import_tasks: system.yml
  tags: system

- import_tasks: user.yml
  tags: [system, user]

- import_tasks: wrapper.yml
  tags: [wrapper, dev]

- import_tasks: staging.yml
  tags: [staging, dev]

- name: Looking for {{ dev_bindir }}/harmony
  local_action: stat path="{{ dev_bindir }}/harmony"
  register: dev_bin
  tags: dev

- name: Install harmony dev bin
  import_tasks: dev.yml
  when: dev_bin.stat.exists
  tags: dev
