---
- import_tasks: system.yml
  tags: system

- import_tasks: user.yml
  tags: [system, user]

- name: Looking for {{ dev_bindir }}/harmony
  local_action: stat path="{{ dev_bindir }}/harmony"
  register: dev_bin
  tags: dev

- name: "***** DEV VERSION (by tag) *****"
  set_fact:
    is_dev: true
  tags: [never, dev]

# has to be done before daemon.yml, sets up harmony_dev var
- name: Install harmony dev bin
  import_tasks: dev.yml
  when: dev_bin.stat.exists and is_dev
  tags: dev

- import_tasks: bls.yml
  tags: [bls, dev]

- import_tasks: daemon.yml
  tags: [daemon, dev]

- import_tasks: db.yml
  tags: [db, dev]

- import_tasks: install.yml
  tags: [install, dev]
