  - name: Check if we have shard {{ shard }} db
    stat:
      path: "{{ harmony_home }}/harmony_db_{{ shard }}/LOCK"
    register: db

  - name: rclone db{{ shard }}
    become: true
    become_user: "{{ harmony_user }}"
    command: "rclone sync -P hmy://pub.harmony.one/mainnet.min/harmony_db_{{ shard }} {{ harmony_home }}/harmony_db_{{ shard }}"
    when: not db.stat.exists
