---
- name: Install harmony bins to staging
  copy:
    src: "files/bin/{{ item }}"
    dest: "{{ harmony_home }}/staging/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  with_items:
    - harmony
    - wallet
  register: staging_bins

- name: Install harmony libs to staging
  copy:
    src: "{{ item }}"
    dest: "{{ harmony_home }}/staging/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  with_fileglob:
    - files/bin/lib*
  register: staging_libs

- name: Install harmony checksum file
  copy:
    src: "files/bin/harmony-checksums.txt"
    dest: "{{ harmony_home }}/"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: preserve
  register: checksums

- name: Transfer staging files to live
  include_tasks: update.yml
  loop: "{{ ['harmony'] + staging_libs.results | map(attribute='item') | list }}"
  when: staging_bins.changed or staging_libs.changed or checksums.changed
