---
  - name: Install harmonyd sysctl.d file
    become: true
    copy:
      src: files/etc/sysctl.d/harmony-sysctl.conf
      dest: /etc/sysctl.d/99-harmony.conf
      mode: '0644'
      owner: root
      group: root
    notify: "sysctl reload"

  - name: Increase default nproc for systemd services
    become: true
    replace:
      path: /etc/systemd/system.conf
      regexp: '^#*DefaultLimitNPROC=.*'
      replace: 'DefaultLimitNPROC=65535'
      backup: yes
    notify: "systemd reload"

  - name: Increase default nofiles for systemd services
    become: true
    replace:
      path: /etc/systemd/system.conf
      regexp: '^#*DefaultLimitNOFILE=.*'
      replace: 'DefaultLimitNOFILE=65535'
      backup: yes
    notify: "systemd reload"
