---
  - name: Install harmonyd sysctl.d file
    copy:
      src: files/etc/sysctl.d/harmony-sysctl.conf
      dest: /etc/sysctl.d/99-harmony.conf
      mode: '0644'
      owner: root
      group: root
    notify: "sysctl reload"

  - name: Reduce journald console output
    replace:
      path: /etc/systemd/journald.conf
      regexp: '^#*MaxLevelConsole=.*'
      replace: 'MaxLevelConsole=crit'
      backup: yes
    notify: "systemd-journald restart"

  - name: Install aptitude, dnsutils, jq, vim
    apt:
      name: [ aptitude, dnsutils, jq, vim ]
      update_cache: yes

  - name: Install latest rclone
    apt:
      deb: https://downloads.rclone.org/v1.52.3/rclone-v1.52.3-linux-amd64.deb
