- name: Set up facts for "{{ item }}"
  set_fact:
    sname: "{{ harmony_home }}/staging/{{ item | basename }}"
    dname: "{{ harmony_home }}/{{ item | basename }}"

- name: Make room for "{{ item }}" backup
  file:
    path: "{{ dname }}.bak"
    state: absent

- name: Move existing "{{ item }}" to backup
  command: mv "{{ dname }}" "{{ dname }}.bak"
  args:
    creates: "{{ dname }}.bak"
  ignore_errors: yes

- name: Update harmony "{{ item }}" from staging
  copy:
    src: "{{ sname }}"
    dest: "{{ dname }}"
    remote_src: true
    mode: preserve
  notify: harmony restart
