- name: Set up facts for "{{ item }}"
  set_fact:
    sname: "{{ harmony_home }}/staging/{{ item }}"
    dname: "{{ harmony_home }}/{{ item }}"

- name: Move existing "{{ item }}" to backup
  command: mv -f "{{ dname }}" "{{ dname }}.bak"
  args:
    creates: "{{ dname }}.bak"
  ignore_errors: yes

- name: Update harmony "{{ item }}" from staging
  copy:
    src: "{{ sname }}"
    dest: "{{ dname }}"
    remote_src: true
    mode: preserve
  notify: harmony restart
