---
  - name: Make harmony home directory parent
    file:
      path: '{{ harmony_home.split("/")[0:-1]|join("/") }}'
      state: directory
      mode: '0755'

  - name: Add harmony user
    user:
      name: "{{ harmony_user }}"
      comment: Harmony Role Account
      create_home: true
      home: "{{ harmony_home }}"
      shell: "/bin/bash"
    ignore_errors: yes

  - name: Make harmony staging directory
    file:
      path: "{{ harmony_home }}/staging"
      state: directory
      owner: "{{ harmony_user }}"
      group: "{{ harmony_user }}"
      mode: '0755'

# - name: Make harmony user keystore
#   file:
#     path: "{{ harmony_home }}/.hmy/keystore/"
#     state: directory
#     owner: "{{ harmony_user }}"
#     group: "{{ harmony_user }}"
#     mode: '0755'

# - name: Send keystore file(s)
#   copy:
#     src: "{{ item }}"
#     dest: "{{ harmony_home }}/.hmy/keystore/"
#     owner: "{{ harmony_user }}"
#     group: "{{ harmony_user }}"
#     mode: '0600'
#   with_fileglob:
#     - credentials/{{ ansible_hostname }}/keystore/*

  - name: Send BLS
    copy:
      src: "{{ item }}"
      dest: "{{ harmony_home }}/{{ item | basename }}"
      owner: "{{ harmony_user }}"
      group: "{{ harmony_user }}"
      mode: '0600'
    with_fileglob:
      - credentials/{{ ansible_hostname }}/bls/UTC--*Z--bls_*
      - credentials/{{ ansible_hostname }}/bls/*.key

# - set_fact:
#     passphrase_file: "credentials/{{ ansible_hostname }}/bls/passphrase"

  - name: Send BLS passphrase
    copy:
      #content: "{{ lookup('file',passphrase_file) | trim }}"
      src: "credentials/{{ ansible_hostname }}/bls/passphrase"
      dest: "{{ harmony_home }}/.passphrase"
      owner: "{{ harmony_user }}"
      group: "{{ harmony_user }}"
      mode: '0600'
