---
- name: Add harmony user
  user:
    name: "{{ harmony_user }}"
    comment: Harmony Role Account
    create_home: true
    home: "{{ harmony_home }}"
    shell: "/bin/bash"
  ignore_errors: yes

- name: Make harmony staging and log directory
  file:
    path: "{{ harmony_home }}/{{ item }}"
    state: directory
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: '0755'
  loop:
    - staging
    - latest

- name: Make rclone config directory
  file:
    path: "{{ harmony_home }}/.config/rclone"
    state: directory
    mode: '0755'

- name: Configure rclone
  copy:
    src: "rclone.conf"
    dest: "{{ harmony_home }}/.config/rclone/rclone.conf"
    owner: "{{ harmony_user }}"
    group: "{{ harmony_user }}"
    mode: '0644'
