  - import_tasks: tasks/user.yml # requires harmony_user to make pidfile dir

  - set_fact:
      bn_ma: '/ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9,/ip4/13.113.101.219/tcp/12019/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/99.81.170.167/tcp/12019/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj'

  - name: Install harmonyd daemon wrapper config
    template:
      src: templates/harmonyd.j2
      dest: /etc/default/harmonyd
      mode: '0644'
      owner: root
      group: root

  - name: Install harmonyd daemon wrapper
    copy:
      src: files/sbin/harmonyd
      dest: /usr/local/sbin/
      mode: '0755'
      owner: root
      group: root
    notify: "systemd reload"

  - name: Install harmonyd systemd unit file
    template:
      src: templates/harmony.service.j2
      dest: /etc/systemd/system/harmony.service
      mode: '0644'
      owner: root
      group: root
    notify: "systemd reload"

  - name: Enable harmony unit file
    systemd:
      name: "{{ harmony_user }}"
      enabled: yes
      masked: no
