  - import_tasks: tasks/user.yml # requires harmony_user to make pidfile dir

  - set_fact:
      harmony_mode: "--is_genesis"

  - set_fact:
      harmony_mode: "--is_genesis=false -is_explorer -shard_id={{ shard_id }}"
    when: is_explorer is defined and is_explorer

  - name: Install harmonyd daemon wrapper config
    template:
      src: templates/harmonyd.j2
      dest: /etc/default/harmonyd
      mode: '0644'
      owner: root
      group: root

  - name: Install harmonyd daemon wrapper
    copy:
      src: files/sbin/harmonyd
      dest: /usr/local/sbin/
      mode: '0755'
      owner: root
      group: root
    notify: "systemd reload"

  - name: Install harmonyd systemd unit file
    template:
      src: templates/harmony.service.j2
      dest: /etc/systemd/system/harmony.service
      mode: '0644'
      owner: root
      group: root
    notify: "systemd reload"

  - name: Enable harmony unit file
    systemd:
      name: "{{ harmony_user }}"
      enabled: yes
      masked: no
