  - import_tasks: tasks/user.yml # requires harmony_user to make pidfile dir

  - set_fact:
      bn_ma: "/ip4/100.26.90.187/tcp/9874/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/54.213.43.194/tcp/9874/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9"

  - name: Install harmonyd daemon wrapper config
    become: true
    template:
      src: templates/harmonyd.j2
      dest: /etc/default/harmonyd
      mode: '0644'
      owner: root
      group: root

  - name: Make harmonyd pidfile directory
    become: true
    file:
      path: /run/harmonyd/
      state: directory
      mode: '0755'
      owner: "{{ harmony_user }}"
      group: "{{ harmony_user }}"

  - name: Install harmonyd daemon wrapper
    become: true
    copy:
      src: files/sbin/harmonyd
      dest: /usr/local/sbin/
      mode: '0755'
      owner: root
      group: root

  - name: Install harmonyd systemd unit file
    become: true
    template:
      src: templates/harmony.service.j2
      dest: /etc/systemd/system/harmony.service
      mode: '0644'
      owner: root
      group: root
    notify: "systemd reload"

  - name: Enable harmony unit file
    become: true
    systemd:
      name: "{{ harmony_user }}"
      enabled: yes
      masked: no
