#!/bin/bash

. /etc/default/harmonyd

rm -rf .dht-* # NTL let's be rude; remove DHT cache

set -x
exec ./harmony${DEV} ${MODE} \
    --run.shard="${SHARD_ID}" \
    --verbosity="${VERBOSITY}" \
    --bls.dir blskeys \
    --bls.pass.file /dev/null
#   --bls.pass false # Apparently not equivalent to file:/dev/null
