#!/usr/bin/env python3

import os, sys, time
import traceback
import re, json, subprocess, requests

#from dateutil import parser

def print_err(*args):
    print(args, file=sys.stderr, flush=True)

## JSON-RPC
def json_rpc(url, method, params=[]):
    if url == None:
        url = os.getenv("HMY_URL", "http://localhost:9500/")

    headers = {'Content-Type':'application/json'}
    req = {"jsonrpc":"2.0","method":method,"params":params,"id":1337}
    resp = requests.post(url, data=json.dumps(req), headers=headers)
    if resp.status_code != 200 or len(resp.content) == 0:
        print_err(f"{method} failed: {resp.status_code}: {resp.content.decode()}")
        return []
    return resp.json()

def get_hmy_block_number(url=None, old=None):
    resp = json_rpc(url, "hmyv2_blockNumber")
    if not 'result' in resp:
        print_err("blockNumber", resp)
        return old
    return resp['result']

def get_hmy_tx(tx, url=None):
    resp = json_rpc(url, "hmyv2_getTransactionByHash", params=[tx])
    if not 'result' in resp:
        print_err(f"getTransactionByHash({tx})", resp)
        return None
    return resp['result']

def get_hmy_block(num, url=None):
    resp = json_rpc(url, "hmyv2_getBlockByNumber", params=[num, {"fullTx":True,"inclTx":True,"InclStaking":True}])
    if not 'result' in resp:
        print_err(f"getBlockByNumber({num})", resp)
        return None
    return resp['result']

#def get_hmy_peer_count(url=None, old=None):
#    resp = json_rpc(url, "net_peerCount")
#    if not 'result' in resp:
#        print_err("net_peerCount", resp)
#        return old
#    return int(resp['result'], 0)

def get_hmy_status(url=None):
    resp = json_rpc(url, "hmyv2_syncing")
    if not 'result' in resp:
        print_err("syncing", resp)
        return 'Error'
    return 'Syncing' if resp['result'] else 'Synced'

def get_hmy_metadata(url=None):
    resp = json_rpc(url, "hmy_getNodeMetadata")
    if not 'result' in resp:
        print_err("getNodeMetadata", resp)
        return
    return resp['result']

#def get_hmy_epoch(url=None, old=None):
#    resp = json_rpc(url, "hmyv2_getEpoch")
#    if not 'result' in resp:
#        print_err("getEpoch", resp)
#        return old
#    return resp['result']

# FIXME: use centralized external ref
def get_hmy_highest_block_number(shard, old=None):
    return get_hmy_block_number(url=f"https://api.s{shard}.t.hmny.io/", old=old)

# FIXME: use centralized external ref
def get_hmy_latest_version(shard=0):
    meta = get_hmy_metadata(f"https://api.s{shard}.t.hmny.io/")
    version = meta['version'].split(',')[1].strip()
    return version.split(' ')[1].strip()

#def get_version():
#    home = os.getenv("HARMONY_HOME", "/data/harmony")
#    cmd = f"{home}/harmony -version 2>&1 | cut -f 6 -d ' '"
#    return subprocess.check_output(cmd, shell=True).decode('utf-8').strip()

class State:
    def __init__(self):
        now = time.time()
        self.time = time.ctime(now)
        self.level = "info"
        self.version = ""

        self.peer_count = -1
        self.id = ""

        self.block_number = -1
        self.highest_block_number = -1
        self.blocks_behind = 0
        self.latest_hash = ''
        self.latest_block_time = ''
        self.status = "Offline"
        self.message = "Offline"

        self.harmony = {}
        self.update()

    def update(self):
        try:
            self.unsafe_update()
        except:
            exc_type, exc_value, exc_traceback = sys.exc_info()
            traceback.print_exception(exc_type, exc_value, exc_traceback, limit=4, file=sys.stderr)
            sys.stderr.flush()
            self.message = f"{exc_type}: {exc_value}"
            self.bump_level('fatal')

    def unsafe_update(self):
        now = time.time()
        self.time = time.ctime(now)
        self.level = 'info'

        self.status = get_hmy_status()
        self.message = self.status

        meta = get_hmy_metadata()
        #print(meta)
        version = meta['version'].split(',')[1].strip()
        self.version = version.split(' ')[1].strip()

        self.peer_count = meta['p2p-connectivity']['connected']
        self.block_number = get_hmy_block_number(old=self.block_number)

        self.harmony['blskeys'] = ','.join(meta['blskey'])
        self.harmony['epoch'] = meta['current-epoch']
        shard = meta['shard-id']
        if shard<0:
            print_err("Failed to find shard")
            return
        self.harmony['shard'] = shard

        self.id = f"shard-{shard}"
        self.latest_version = get_hmy_latest_version(shard)
        self.needs_update = self.version != self.latest_version

        self.highest_block_number = get_hmy_highest_block_number(shard, old=self.highest_block_number)
        if self.highest_block_number > 0:
            self.blocks_behind = self.highest_block_number - self.block_number
        if self.blocks_behind > 100:
            self.bump_level('error')
        elif self.blocks_behind > 10:
            self.bump_level('warn')

        latest_block = get_hmy_block(self.block_number)
        if latest_block!=None and 'hash' in latest_block:
            self.latest_hash = latest_block['hash']
            self.latest_block_time = time.ctime(latest_block['timestamp'])
        else:
            print_err("Failed to find latest block")

    def __str__(self):
        return json.dumps(self.__dict__)

    def bump_level(self, level):
        Levels = {'info': 0, 'warn': 1, 'error': 2, 'fatal': 3}
        if Levels[level]>Levels[self.level]:
            self.level = level

def main():
    output = os.getenv("COLLECTOR_LOG", None)
    period = int(os.getenv("COLLECTOR_PERIOD", 0))

    state = State()

    while True:
        if output == None:
            print(state)
        else:
            with open(output, "a") as myfile:
                myfile.write(str(state)+"\n")
                myfile.close()

        if period <= 0:
            break;

        time.sleep(period)
        state.update()

if __name__ == "__main__":
    main()

# vim: expandtab
